// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountUsers(ctx context.Context, search string) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	ListUsersCreatedAtAsc(ctx context.Context, arg ListUsersCreatedAtAscParams) ([]User, error)
	ListUsersCreatedAtDesc(ctx context.Context, arg ListUsersCreatedAtDescParams) ([]User, error)
	ListUsersIdAsc(ctx context.Context, arg ListUsersIdAscParams) ([]User, error)
	ListUsersIdDesc(ctx context.Context, arg ListUsersIdDescParams) ([]User, error)
	RestoreUser(ctx context.Context, userUuid uuid.UUID) (User, error)
	SoftDelete(ctx context.Context, userUuid uuid.UUID) (User, error)
	TrashUser(ctx context.Context, userUuid uuid.UUID) (User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
